# Generated by Django 3.1.7 on 2022-01-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weavingSearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodicals',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=100, primary_key=True, serialize=False)),
                ('article_url', models.TextField(default='', max_length=1000)),
                ('category', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('authors', models.CharField(default='', max_length=255)),
                ('company_list', models.CharField(default='', max_length=255)),
                ('keywords', models.CharField(default='', max_length=255)),
                ('abstract', models.TextField(default='', max_length=2000)),
            ],
            options={
                'db_table': 'literature',
            },
        ),
        migrations.DeleteModel(
            name='Guiding',
        ),
    ]
