# Generated by Django 3.1.7 on 2022-01-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weavingSearch', '0002_auto_20220123_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicals',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
