# Generated by Django 3.1.7 on 2022-02-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weavingSearch', '0003_auto_20220123_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('inventor', models.CharField(default='', max_length=255)),
                ('applicant', models.CharField(default='', max_length=255)),
                ('sq_date', models.DateField(default='')),
                ('gk_date', models.DateField(default='')),
                ('url', models.TextField(default='', max_length=1000)),
                ('guo_bie', models.CharField(default='', max_length=255)),
                ('bh', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'patent',
            },
        ),
    ]
