# Generated by Django 3.1.7 on 2022-01-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='编号')),
                ('url', models.CharField(max_length=255, verbose_name='链接')),
                ('introduction', models.CharField(default='', max_length=100, verbose_name='简介')),
            ],
        ),
    ]
