# Generated by Django 3.1.7 on 2022-03-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weavingPicture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('company', models.CharField(default='/', max_length=255, verbose_name='单位')),
                ('area', models.CharField(default='/', max_length=255, verbose_name='领域')),
                ('total_papers', models.IntegerField(default=0, max_length=10, verbose_name='发文数')),
                ('main_art1', models.TextField(default='/', max_length=1000, verbose_name='代表作1')),
                ('main_art2', models.TextField(default='/', max_length=1000, verbose_name='代表作2')),
                ('main_art3', models.TextField(default='/', max_length=1000, verbose_name='代表作2')),
            ],
        ),
    ]
