# Generated by Django 3.1.7 on 2022-01-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weavingCharts', '0002_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
