# Generated by Django 3.1.7 on 2022-02-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weavingCharts', '0003_auto_20220126_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
                ('date', models.CharField(default='', max_length=255)),
                ('abstract', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
