# Generated by Django 3.1.7 on 2022-02-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weavingCharts', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
